### ISSUE TITLE
NewEvents stucks

### ISSUE THREAD

**Issue by bhugot** [microsoft/durabletask-mssql#198]
Hello, 

While watching our process I see that some CompletedTask events stay in NewEvents table for really long time (hours)
while other events are removed quite fast (for same type of orchestration).  They are finally processed.

As I already posted we also met 2 "duplications" problems (sometimes due to a restart of an instance).

1.  2 events for same task for same instanceId
2.  1 events for an already completed task (we can see this in appinsight )
    

>  System.InvalidCastException: Unable to cast object of type 'DurableTask.Core.History.TaskCompletedEvent' to type 'DurableTask.Core.History.TaskScheduledEvent'.
   at DurableTask.Core.TaskOrchestrationDispatcher.ReconcileMessagesWithState(TaskOrchestrationWorkItem workItem, String dispatcher, ErrorPropagationMode errorPropagationMode, LogHelper logHelper) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 860
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 345
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem)
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 211
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 373

**Comment by cgillum** [comment]
Thanks for reporting this. I was able to do a search and confirm that we're seeing some events like this in production. More investigation is needed to determine the root cause.

**Comment by cgillum** [comment]
I found the issue for the exception you are seeing. The two linked PRs should fix it.

**Comment by bhugot** [comment]
Hello @cgillum Are you releasing it today?

**Comment by cgillum** [comment]
@bhugot yes, this is released now: https://github.com/microsoft/durabletask-mssql/releases/tag/v1.2.2.

I think the local fix to this package should be sufficient to fix the error you're seeing. If I'm wrong, however, then we'll need to wait for the next version of Microsoft.Azure.DurableTask.Core to come out.

**Comment by bhugot** [comment]
Ok I will try it :)

**Comment by bhugot** [comment]
It's working way better no more stuck process :)
